# Generated by Django 5.2.10 on 2026-02-05 04:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryFingerprintModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('table_name', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('query_type', models.CharField(max_length=50)),
                ('fingerprint_hash', models.CharField(db_index=True, max_length=64)),
                ('filters_json', models.JSONField()),
                ('epsilon_cost', models.FloatField()),
                ('budget_multiplier', models.FloatField(default=1.0)),
                ('effective_cost', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('result_value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'query_fingerprints',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', '-timestamp'], name='query_finge_user_id_1ec73c_idx'), models.Index(fields=['fingerprint_hash'], name='query_finge_fingerp_c8f115_idx'), models.Index(fields=['table_name', 'field_name'], name='query_finge_table_n_a287fa_idx')],
            },
        ),
    ]
