# Generated by Django 5.2.10 on 2026-02-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_team_teammembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacybudgettransaction',
            name='noise_deterministic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='privacybudgettransaction',
            name='noise_seed_window',
            field=models.CharField(default='', max_length=50),
        ),
    ]
