# Generated by Django 5.2.10 on 2026-06-10 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0005_privacybudgettransaction_noise_deterministic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacybudgettransaction',
            name='noise_deterministic',
        ),
        migrations.RemoveField(
            model_name='privacybudgettransaction',
            name='noise_seed_window',
        ),
    ]
