"""
Django settings for proj project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import os
import dj_database_url
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-ve1ptm4zahjwnv*o_)g0!&iuzyq0xv&p7s$hyzny*xsqu+wwpy')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.onrender.com',  # Allow all Render subdomains
    '*'  # Remove this in production after testing
]


# Application definition

INSTALLED_APPS = [
    'rest_framework', 
    'risk_assessment',
    'proj.apps.ProjConfig',  # Privacy budget models
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For static files in production
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'proj.urls'


WSGI_APPLICATION = 'proj.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse(
        os.environ.get("DATABASE_URL", "sqlite:///db.sqlite3")
    )
}



# Password validation removed - authentication disabled
# No auth system in use



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Add this at the bottom
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    # Disable authentication to avoid dependency on django.contrib.auth
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
    'UNAUTHENTICATED_USER': None,
    'UNAUTHENTICATED_TOKEN': None,
}




MIGRATION_MODULES = {
    'auth': None,
    'contenttypes': None,
    'admin': None,
    'sessions': None,
}


# ============================================================================
# DIFFERENTIAL PRIVACY NOISE CONFIGURATION
# ============================================================================

# Secret key for deterministic noise generation
# CRITICAL: Keep this secret! Rotate periodically.
# In production, set via environment variable: DP_NOISE_SECRET_KEY
DP_NOISE_SECRET_KEY = os.environ.get(
    'DP_NOISE_SECRET_KEY',
    'INSECURE_DEFAULT_DEV_KEY_CHANGE_IN_PRODUCTION_f8a3b2c1d4e5'  # Dev only
)

# Noise seed rotation window (in hours)
# Default: 24 hours (daily rotation)
# Options: 1 (hourly), 24 (daily), 168 (weekly)
DP_SEED_ROTATION_HOURS = int(os.environ.get('DP_SEED_ROTATION_HOURS', '24'))

