# Generated by Django 5.2.10 on 2026-02-04 08:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyBudgetLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('max_epsilon', models.FloatField(default=10.0)),
                ('epsilon_remaining', models.FloatField(default=10.0)),
                ('last_refill', models.DateTimeField(default=django.utils.timezone.now)),
                ('global_seed', models.BinaryField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'privacy_budget_ledgers',
                'indexes': [models.Index(fields=['user_id'], name='privacy_bud_user_id_810979_idx'), models.Index(fields=['updated_at'], name='privacy_bud_updated_1c5b43_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrivacyBudgetRefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('refill_amount', models.FloatField()),
                ('epsilon_before', models.FloatField()),
                ('epsilon_after', models.FloatField()),
                ('refill_type', models.CharField(choices=[('AUTOMATIC', 'Automatic (Sliding Window)'), ('ADMIN', 'Admin Manual Reset'), ('SCHEDULED', 'Scheduled Refill')], max_length=50)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refills', to='proj.privacybudgetledger')),
            ],
            options={
                'db_table': 'privacy_budget_refills',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyBudgetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('query_type', models.CharField(max_length=50)),
                ('epsilon_cost', models.FloatField()),
                ('epsilon_remaining', models.FloatField()),
                ('mechanism_used', models.CharField(max_length=100)),
                ('sensitivity', models.FloatField(default=0.0)),
                ('noise_scale', models.FloatField(default=0.0)),
                ('degradation_factor', models.FloatField(default=1.0)),
                ('bounds_lower', models.FloatField(default=0.0)),
                ('bounds_upper', models.FloatField(default=0.0)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='proj.privacybudgetledger')),
            ],
            options={
                'db_table': 'privacy_budget_transactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ledger', '-timestamp'], name='privacy_bud_ledger__b9090b_idx'), models.Index(fields=['query_id'], name='privacy_bud_query_i_0e4970_idx'), models.Index(fields=['timestamp'], name='privacy_bud_timesta_8ac6b6_idx')],
            },
        ),
    ]
