# Generated by Django 5.2.10 on 2026-02-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacybudgetledger',
            name='team_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
