# Generated by Django 5.2.10 on 2026-02-05 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_privacybudgetledger_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('team_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_members', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('shared_budget', models.BooleanField(default=False)),
                ('team_epsilon', models.FloatField(blank=True, default=10.0, null=True)),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proj.team')),
            ],
            options={
                'db_table': 'team_memberships',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['user_id', 'team'], name='team_member_user_id_6012dd_idx')],
            },
        ),
    ]
