# Generated by Django 5.2.10 on 2026-06-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0005_privacybudgettransaction_noise_deterministic_and_more'),
        ('proj', '0006_remove_noise_seed_window'),
    ]

    operations = [
    ]
