# Generated by Django 5.2.10 on 2026-01-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField(db_index=True, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('area_type', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=50)),
                ('occupation', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('monthly_income', models.IntegerField()),
                ('household_size', models.IntegerField()),
                ('marital_status', models.CharField(max_length=20)),
                ('disability', models.CharField(max_length=10)),
                ('chronic_illness', models.CharField(max_length=10)),
                ('migration_status', models.CharField(max_length=50)),
                ('employment_type', models.CharField(max_length=50)),
                ('land_owned_acres', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demographic Record',
                'verbose_name_plural': 'Demographic Records',
                'db_table': 'demographic_records',
                'ordering': ['record_id'],
            },
        ),
    ]
