# Generated by Django 5.2.10 on 2026-01-30 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(db_index=True, max_length=255)),
                ('row_index', models.IntegerField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dataset_records',
                'unique_together': {('dataset_name', 'row_index')},
            },
        ),
        migrations.DeleteModel(
            name='DemographicRecord',
        ),
    ]
