# Generated by Django 5.2.10 on 2026-02-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment', '0002_datasetrecord_delete_demographicrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasetrecord',
            options={'ordering': ['dataset_name', 'row_index']},
        ),
        migrations.AlterUniqueTogether(
            name='datasetrecord',
            unique_together=set(),
        ),
    ]
